export const GET_JOBS = "GET_JOBS";
export const SET_JOBS = "SET_JOBS";

export const SET_JOB_COUNT = "SET_JOB_COUNT";

export const SET_ACTIVE_JOB = "SET_ACTIVE_JOB";
export const GET_ACTIVE_JOB = "GET_ACTIVE_JOB";
export const DELETE_ACTIVE_JOB = "DELETE_ACTIVE_JOB";

export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";

export const UPDATE_JOB_REQUEST = "UPDATE_JOB_REQUEST";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";

export const JD_CREATE_REQUEST = "JD_CREATE_REQUEST";
export const JD_CREATE_SUCCESS = "JD_CREATE_SUCCESS";
export const UNSET_JD_CREATE = "UNSET_JD_CREATE";

export const JD_UPDATE_REQUEST = "JD_UPDATE_REQUEST";
export const JD_UPDATE_SUCCESS = "JD_UPDATE_SUCCESS";
export const UNSET_JD_UPDATE = "UNSET_JD_UPDATE";

export const SET_AFTER_CREATE_JOB = "SET_AFTER_CREATE_JOB";
