export const GET_JOBS_FOR_MATCHING = "GET_JOBS_FOR_MATCHING";
export const SET_JOBS_FOR_MATCHING = "SET_JOBS_FOR_MATCHING";
export const SET_JOBS_FOR_MATCHING_COUNT = "SET_JOBS_FOR_MATCHING_COUNT";

export const GET_MATCHING_ACTIVITIES = "GET_MATCHING_ACTIVITIES";
export const SET_MATCHING_ACTIVITIES = "SET_MATCHING_ACTIVITIES";
export const SET_JOB_MATCHING_ACTIVITIES = "SET_JOB_MATCHING_ACTIVITIES";

export const CREATE_MATCHING_ACTIVITY_REQUEST = "CREATE_MATCHING_ACTIVITY_REQUEST";
export const CREATE_MATCHING_ACTIVITY_SUCCESS = "CREATE_MATCHING_ACTIVITY_SUCCESS";

export const GET_MATCHING_ACTIVITY_DETAILS = "GET_MATCHING_ACTIVITY_DETAILS";
export const UPDATE_MATCHING_ACTIVITY_DETAILS = "UPDATE_MATCHING_ACTIVITY_DETAILS";

export const GET_MATCHED_TALENTS_REQUEST = "GET_MATCHED_TALENTS_REQUEST";
export const GET_MATCHED_TALENTS_SUCCESS = "GET_MATCHED_TALENTS_SUCCESS";
export const SET_SEARCHED_MATCHED_TALENTS_COUNT = 'SET_SEARCHED_MATCHED_TALENTS_COUNT';
export const GET_SEARCHED_MATCHED_TALENTS = 'GET_SEARCHED_MATCHED_TALENTS';