export const CREATE_TALENT_REQUEST = `CREATE_TALENT_REQUEST`;
export const CREATE_TALENT_SUCCESS = `CREATE_TALENT_SUCCESS`;

export const GET_TALENTS = `GET_TALENTS`;
export const SET_TALENTS = `SET_TALENTS`;

export const SET_TALENT_COUNT = `SET_TALENT_COUNT`;

export const GET_ACTIVE_TALENT = `GET_ACTIVE_TALENT`;
export const SET_ACTIVE_TALENT = `SET_ACTIVE_TALENT`;
export const DELETE_ACTIVE_TALENT = `DELETE_ACTIVE_TALENT`;

export const UPDATE_TALENT_REQUEST = "UPDATE_TALENT_REQUEST";
export const UPDATE_TALENT_SUCCESS = "UPDATE_TALENT_SUCCESS";

export const RESUME_CREATE_REQUEST = "RESUME_CREATE_REQUEST";
export const RESUME_CREATE_SUCCESS = "RESUME_CREATE_SUCCESS";
export const UNSET_RESUME_CREATE = "UNSET_RESUME_CREATE";

export const RESUME_UPDATE_REQUEST = "RESUME_UPDATE_REQUEST";
export const RESUME_UPDATE_SUCCESS = "RESUME_UPDATE_SUCCESS";
export const UNSET_RESUME_UPDATE = "UNSET_RESUME_UPDATE";

export const SET_AFTER_CREATE_TALENT = "SET_AFTER_CREATE_TALENT";
